const countries = [
  {"value":"","descr":"-"},
  {"value":"GB","descr":"UK"},
  {"value":"NB","descr":"UK (N. IRELAND)"},
  {"value":"AT","descr":"AUSTRIA"},
  {"value":"BY","descr":"BELARUS"},
  {"value":"BE","descr":"BELGIUM"},
  {"value":"BG","descr":"BULGARIA"},
  {"value":"HR","descr":"CROATIA"},
  {"value":"CZ","descr":"CZECH REPUBLIC"},
  {"value":"DK","descr":"DENMARK"},
  {"value":"EE","descr":"ESTONIA"},
  {"value":"FI","descr":"FINLAND"},
  {"value":"FR","descr":"FRANCE"},
  {"value":"DE","descr":"GERMANY"},
  {"value":"GR","descr":"GREECE"},
  {"value":"HU","descr":"HUNGARY"},
  {"value":"IS","descr":"ICELAND"},
  {"value":"IE","descr":"IRELAND"},
  {"value":"IT","descr":"ITALY"},
  {"value":"LV","descr":"LATVIA"},
  {"value":"LT","descr":"LITHUANIA"},
  {"value":"LU","descr":"LUXEMBOURG"},
  {"value":"MC","descr":"MONACO"},
  {"value":"NL","descr":"NETHERLANDS"},
  {"value":"NO","descr":"NORWAY"},
  {"value":"PL","descr":"POLAND"},
  {"value":"PT","descr":"PORTUGAL"},
  {"value":"RO","descr":"ROMANIA"},
  {"value":"RU","descr":"RUSSIA"},
  {"value":"SK","descr":"SLOVAKIA"},
  {"value":"SI","descr":"SLOVENIA"},
  {"value":"ES","descr":"SPAIN"},
  {"value":"SE","descr":"SWEDEN"},
  {"value":"CH","descr":"SWITZERLAND"},
  {"value":"TR","descr":"TURKEY"}]
export default countries;